#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun  6 14:55:10 2020

@author: sny
"""

from 1D-CA import *
from parameters import *
import sys

def run_seeds(seed_):
   dirname = os.path.dirname(__file__)
   for line in fileinput.input(dirname+"/parameters.py", inplace=True):
        if 'seed' in line:
            print("seed={}".format(seed_))
            
   main()

if __name__ == '__main--':
   seedlist = [1,2,3,4,5,6,7,8,9,10]
   
   for seed in seedlist():
      main()

   
   